#!/bin/bash

export TZ=UTC

cd $(dirname $0)

# We're assuming this is the dev env so use watch for that.

./watch &
WATCH_PID=$!

function kill_autobuild {
	echo KILL $WATCH_PID
	kill $WATCH_PID
}

trap kill_autobuild EXIT

while true
do
	# TODO: when the module loader is no longer experimental,
	# remove the filter. (Bash-only;
	# https://unix.stackexchange.com/questions/3514/how-to-grep-standard-error-stream-stderr)
	node --experimental-modules ./server/main.mjs \
		2> >(grep -v "The ESM module loader is experimental")
	RESULT=$?
	# Result 1 means "I crashed (syntax error or something)"
	if [ "$RESULT" -eq 1 ]
	then
		echo
		echo "Fix the error and I'll try again, or Ctrl-C to quit."
		echo

		# This moderately well working piece of magic is necessary for chokidar-cli to quit
		# when it sees change. Really.
		chokidar 'server/**/*.mjs' 'common/**/*.mjs' -c 'ps -ef | egrep chokidar | egrep "[ ]node" | awk "{ print \$2 }" | xargs kill -2' \
			>/dev/null 2>/dev/null

		echo "Here we go again:"
		echo ""
	# Result 10 means "restart me"
	elif [ "$RESULT" -eq 10 ]
	then
		:
		# Process wants to restart
	else
		echo "Process exited with result $RESULT"
		exit
	fi
done
