#!/bin/bash

# TODO: when the module loader is no longer experimental,
# remove the filter. (Bash-only;
# https://unix.stackexchange.com/questions/3514/how-to-grep-standard-error-stream-stderr)

export TZ=UTC

cd $(dirname $0)

# Check if we need to do build-dev
if [ ! -f public/redom.mjs ]
then
	./build-dev
fi

node --experimental-modules ./server.mjs 2> >(grep -v "The ESM module loader is experimental")
